[build]
  # Diretório de publicação
  publish = "."

  # Diretório das funções serverless
  functions = "netlify/functions"

  # Comando de build (variáveis já estão no arquivo)
  command = "echo 'Build concluído - usando netlify-env.js existente'"

# Configuração das funções serverless
[functions]
  directory = "netlify/functions"

# Cabeçalhos de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co https://raw.githubusercontent.com https://*.up.railway.app;"

# ZERO cache para HTML (sempre busca versão nova)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# ZERO cache para pages (sempre busca versão nova)
[[headers]]
  for = "/pages/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Sem cache para arquivos dinâmicos
[[headers]]
  for = "/netlify-env.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Cache inteligente para JS/CSS versionados (com ?v= são únicos)
[[headers]]
  for = "/assets/js/*.js"
  [headers.values]
    # Se tem ?v= no URL, pode cachear longamente pois versão é única
    Cache-Control = "public, max-age=31536000"
    # Mas força revalidação se não tem versão
    Vary = "Accept-Encoding"

[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Vary = "Accept-Encoding"

# Cache longo para assets estáticos (imagens, etc)
[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

# Configurações de ambiente
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "staging" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Redirects para as funções serverless
[[redirects]]
  from = "/api/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

# Headers específicos para webhook (CORS)
[[headers]]
  for = "/.netlify/functions/webhook"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"